### ISSUE TITLE
Přidat drát

### ISSUE THREAD

**Issue by beny** [Pajk/ptaci#1]

**Comment by Pajk** [comment]
a odchytávat kolize ptáků s lanem, po sednutí ptáka na lano vymyslet, kam a jak to poznačíme a jestli má smysl vytvářet joint mezi lanem a ptáčkem

**Comment by beny** [comment]
Já si myslím že to nemá smysl nějaký kolize s lanem odchytávat. Stačí, že to lano se hýbe čímž hýbe všemi ptáčky. Akorát bychom si to komplikovali. Navrhuji close - hotovo s tím, že max ještě to lano doladíme.
