### ISSUE TITLE
Vytvořit levely

### ISSUE THREAD

**Issue by Pajk** [Pajk/ptaci#10]
V GameState.mm je třeba nadefinovat jednotlivé levely. 

Jak dlouho se mají vytvářet noví ptáci
        level1.spawnSeconds = 15;
Jak často se má poslat nový pták
        level1.spawnRate = 1;
Druhy ptáků, kteří se vytvářejí, zatím se každou spawnRate sekundu vytvoří všíchni, kteří jsou ve spawnIds.
        [level1.spawnIds addObject:[NSNumber numberWithInt:BirdTypeFast]];
        [level1.spawnIds addObject:[NSNumber numberWithInt:BirdTypeSlow]];
Přidání levelu do hry
        [_levels addObject:level1];

Definování přídávání ptáků
Nejspíš bude předěláno tak, že se tady do definice levelu bude muset zadat počet jednotlivých druhů ptáku, kteří se mají do levelu přidat. Při hře se pak vždy náhodně vybere druh ptáka, vytvoří se a dekrementuje se počet.

**Comment by beny** [comment]
Myslím, že 3 levely stačí až až.
