### ISSUE TITLE
Zaktivovat přepínání levelů

### ISSUE THREAD

**Issue by Pajk** [Pajk/ptaci#11]
Level končí, když jsou "zničení" všíchní ptáci. 
Může skončít úspěchem, pokud je skóre větší, než požadované skóre levelu.
Neúspěch, pokud je skóre menší než požadované skóre.

**Comment by Pajk** [comment]
třeba ještě kontrolovat počet srdíček, pokud nedosáhne požadované výše, tak bude možný restart kola

**Comment by beny** [comment]
Možná bych tohle taky neřešil, protože pokud se mu nepodaří získat srdíčka, tak naopak ztrácí body (špatným párováním).

**Comment by Pajk** [comment]
Nechápu, právě že ztrácí body, ale takhle ta hra nemá žádný cíl. Jen tak je necháš popadat a neřešíš, kolik máš srdíček. Když bude nutné mít alespoň XX srdíček, tak se budeš aspoň snažit. S tím, že pokud to nedáš, tak ti to poví, že si looser a hodí tě to do menu, můžeš začít odznova.

**Comment by beny** [comment]
A cílem nemůže být jen získat co největší počet srdíček? Jako já to chtěl zjednodušit, nepříjde mě to jako blbost, tak jestli chceš, směle do toho.
