### ISSUE TITLE
Doplnit help pro naklánění

### ISSUE THREAD

**Issue by beny** [Pajk/ptaci#16]
Vytvořit jednoduchý obrázek jako help pro naklánění zařízení.

**Comment by beny** [comment]
Nastává tu otázka kam s tím obrázkem, do toho spritebatch se už nevejde tak to buď hodit zvlášť nebo vyházet z toho sprite všechny ty pozadí, dát jej tam jen 1x a pak to skládat v aplikaci (jsem pro tuto variantu pokud nebude náročná.

**Comment by Pajk** [comment]
Tak nechal bych tam určitě pozadí levelu, všechny ostatní můžeme hodit bokem.

**Comment by beny** [comment]
A hodit je cele bokem nebo dát do sprite jen to pozadí a jednotlivé obrázky pak zobrazovat přes to?

**Comment by Pajk** [comment]
Jsem pro to dat je cele bokem. To mi prijde nejjednodussi reseni. Mene prace pro me i pro tebe.

**Comment by beny** [comment]
Jen aby se to pak Heroutovy líbilo tohle řešení.

**Comment by Pajk** [comment]
Myslím, že herout o něm nemusí vědět. Tak připrav teda sprity, uděláme to po tvojem. Potřebujeme teda větší ptáčky, to jest vše. Ty budou v texture atlasu. Pozadí menu bude mimo a pozadí hry bude taky v texture atlasu. Nebo pokud se tam pak vleze vše, tak to tam můžem dát vše.
