### ISSUE TITLE
Sehnat nebo vytvořit hudbu a zvuky

### ISSUE THREAD

**Issue by Pajk** [Pajk/ptaci#5]
Na pozadí to chce nějakou chytlavou, živou muziku, kterou si budem pak pobrukovat celé dny:).

Zvuky budeme potřebovat pro všechny významné události, zatím mě napadají tyto:
- přílet - každý druh ptáka by mohl mít přirazenou jinou skupinu zvuků
- sedne na lano
- dojde ke spárování dvojce
- rvačka
- chycení ptáčka prstem
- konec dotyku, puštění ptáčka

**Comment by Pajk** [comment]
Vzhled má v hlavě tvá přitelkyně, tak možná tam někdé má i zvuky:). Výběr teda nechám na tobě/vás.

**Comment by beny** [comment]
Hotovo, je několik verzí každého efektu + je hudba jedna do menu (cca 2min) a druhá do hry (cca 4min).
