### ISSUE TITLE
Grafika ptáků

### ISSUE THREAD

**Issue by Pajk** [Pajk/ptaci#6]
Vytvořit grafiku pro ptáčky.
Kolik druhů vytvoříš, tolik jich bude. Ze začátku stačí klidně 3.

Ke každému druhu bude třeba vytvořit i animace:
- let - nejspíš mávání křídlama:)
- chycení uživatelem - to by mohl třebat křídlama i nožičkama, pokud nějaké bude mít

Obecně u všech stejné:
- spárování
- rvačka

Další dopíšem, více mě toho teď nenapadá.

**Comment by Pajk** [comment]
Ptacci by meli byt co nejmensi, tak aby byli pekne videt a sli chytnout. To co tam mame ted je prilis velike.

**Comment by beny** [comment]
Myslím že základ je hotov, teďka max ladit další ptáky či animace. Pokud ale bude potřeba tak vytvoř novou issue.
